import { ArrowDownToLine, ArrowUpRight, GraduationCap, Trophy } from 'lucide-react';
import type { Portfolio, Entry } from '@/lib/schema';
import { SectionHeading } from './section-heading';

function Timeline({ entries }: { entries: Entry[] }) { return <div className="timeline">{entries.map((entry) => <article key={entry.id}><div className="timeline-period">{entry.period}</div><div><h3>{entry.title}</h3><p className="organization">{entry.organization}</p><p>{entry.description}</p></div><ArrowUpRight className="timeline-arrow" size={20} /></article>)}{entries.length === 0 && <p>Updates coming soon.</p>}</div>; }
export function AboutJourney({ data }: { data: Portfolio }) { return <>
  <section id="about" className="section shell about-section"><div><SectionHeading number="02" label="THE HUMAN BEHIND THE CODE" title="Curiosity is the constant" /><div className="about-stamp"><span>THINK.</span><span>BUILD.</span><span className="accent">ITERATE. ↗</span><div>HUMAN FIRST. ENGINEER ALWAYS.</div></div></div><div className="about-copy"><p>{data.profile.about}</p><div className="tags large-tags">{data.profile.skills.map((skill) => <span key={skill}>{skill}</span>)}</div>{data.profile.resumeUrl ? <a href={`resume.pdf`} className="button secondary" target="_blank" rel="noopener noreferrer">Download résumé <ArrowDownToLine size={17} /></a> : <span className="resume-pending"><ArrowDownToLine size={17} /> Résumé coming soon</span>}</div></section>
  <section id="experience" className="section shell"><SectionHeading number="03" label="THE JOURNEY" title="Learning. Shipping. Evolving" /><Timeline entries={data.experience} /></section>
  <section id="education" className="section shell"><SectionHeading number="04" label="FOUNDATIONS" title="Built on learning" /><div className="education-grid">{data.education.map((entry) => <article className="info-card" key={entry.id}><GraduationCap className="accent" size={28} /><span className="mono muted">{entry.period}</span><h3>{entry.title}</h3><p className="organization">{entry.organization}</p><p>{entry.description}</p></article>)}</div></section>
  <section id="stack" className="section shell"><SectionHeading number="05" label="TOOLS OF THE TRADE" title="My creative toolkit" description="The languages and frameworks behind the ideas." /><div className="stack-grid">{data.technologies.map((tech) => <div className="tech-card" key={tech.id}><span className="tech-symbol">{tech.symbol}</span><h3>{tech.name}</h3><p>{tech.category}</p></div>)}</div></section>
  <section id="achievements" className="section shell"><SectionHeading number="06" label="MILESTONES" title="Small wins. Forward motion" /><div className="achievement-list">{data.achievements.map((entry) => <article key={entry.id}><Trophy size={25} className="accent" /><div><h3>{entry.title}</h3><p>{entry.description}</p></div><span className="mono muted">{entry.period}</span></article>)}</div></section>
  </>; }
